# Generated by Django 5.0.7 on 2025-03-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUser',
            new_name='Admin',
        ),
    ]
