# Generated by Django 5.0.7 on 2025-03-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0005_salesorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
