# Generated by Django 5.0.7 on 2025-03-08 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0008_alter_salesorder_status_returnorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_app.customer'),
        ),
    ]
