# Generated by Django 5.0.7 on 2025-03-11 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0009_returnorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales_app.customer'),
        ),
    ]
